
<div class="foot clearfix">
    <div class="container">


        <div class="ems70" id="ems70_FooterLegals"><div class="caption" style="display:none">[FooterLegals]</div>

            <div class="ems70marketingContent" data-ad-name="FooterLegals_Guest" data-ad-id="ems70contentContainer_877504">
                <div class="ems70contentContainer" id="ems70contentContainer_877504">

                    <ul>
                        <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=73">Disclaimer</a></li>
                        <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=74">Legal notice</a></li>
                        <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=76">Purchase conditions</a></li>
                        <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=77">Privacy policy / cookies</a></li>
                        <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=82">Provider information</a></li>
                        <li>
                            <a href="/shop-de/en/TermsAndConditionsView?langId=-1&amp;storeId=10">Terms &amp; Conditions of Sale</a>
                        </li>
                    </ul>

                </div>
            </div>

        </div>

        <p class="copy"><strong>© Kramp Groep 2008 - 2016</strong></p>

    </div>
</div>