
<div class="ems70" id="ems70_FooterTop"><div class="caption" style="display:none">[FooterTop]</div>

    <div class="ems70marketingContent" data-ad-name="FooterTop" data-ad-id="ems70contentContainer_641664">
        <div class="ems70contentContainer" id="ems70contentContainer_641664">


            <div class="footertop">
                <div class="numColumn2">
                    <div class="column1">
                        <h1>
                            Contact
                        </h1>
                        <p>
                            If you're interested in finding out what our company can do for you, please contact us.
                        </p>
                        <a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=322" class="btn btn-warning">
                            Contact
                        </a>
                    </div>
                    <div class="column2">
                        <h1>
                            Login / Lost password
                        </h1>
                        <p>
                            Your gateway to Europe's largest range of technical parts.
                            Click here to log in.
                        </p>

                        <a href="/shop-de/en/LogonView?langId=-1&amp;storeId=10" class="btn">
                            Login
                        </a>
                    </div>



                    <div class="clearBoth"></div>
                </div>
            </div>


        </div>
    </div>

</div>