<div class="footer-wrapper">
    <div class="container">


        <div class="ems70" id="ems70_FooterBottom"><div class="caption" style="display:none">[FooterBottom]</div>

            <div class="ems70marketingContent" data-ad-name="cssfix" data-ad-id="ems70contentContainer_668011">
                <div class="ems70contentContainer" id="ems70contentContainer_668011">

                    <style type="text/css">
                        #jsTemplates_addToCart{ display: none; }
                    </style>

                </div>
            </div>

            <div class="ems70marketingContent" data-ad-name="FooterBottom" data-ad-id="ems70contentContainer_641522">
                <div class="ems70contentContainer" id="ems70contentContainer_641522">



                    <style type="text/css">
                        #if("$storeId"=="80")
                        #footer .footer-wrapper{ background: #990000; }
                        #end
                        #jsTemplates_addToCart{ display: none; }
                    </style>
                    <div class="footer-box">
                        <h4 class="footer-box-header"><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=2">About Kramp</a></h4>
                        <ul>
                            <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=3">About Kramp</a></li>        <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=4">Our history</a></li>        <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=5">Our mission &amp; vision</a></li>        <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=6">Our values</a></li>        <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=7">Our strategy</a></li>        <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=862">Sustainability</a></li><li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=1352">Annual Report</a></li>    </ul>
                    </div>

                    <div class="footer-box">
                        <h4 class="footer-box-header"><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=8">It's that easy</a></h4>    <ul>
                            <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=10">Kramp Song</a></li>    </ul>
                        <h4 class="footer-box-header"><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=11">Core business</a></h4>    <ul>
                            <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=12">Our markets</a></li>      <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=13">Our webshop</a></li>      <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=14">Logistics and transport</a></li>      <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=15">Our specialists</a></li>    </ul>
                    </div>

                    <div class="footer-box">
                        <h4 class="footer-box-header"><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=16">Services</a></h4>    <ul>
                            <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=17">Business solutions</a></li>      <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=55">Technical services</a></li>
                            <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=31">Training and education</a></li>          </ul>

                    </div>

                    <div class="footer-box">
                        <h4 class="footer-box-header">More information</h4>
                        <ul>
                            <li><a href="/shop-de/en/BrandsOverview?langId=-1&amp;storeId=10">Our Brands</a></li>

                            <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=32">Kramp Academy</a></li>

                            <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=1052">Help </a></li>

                            <li><a href="http://www.karrierebeikramp.de/" target="_blank">Career at Kramp</a></li>

                            <!-- <li><a href="http://kramp-en.vkf-renzel.de/" target="_blank">Gifts Webshop</a></li> -->

                            <li><a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=322">Contact</a></li>

                        </ul>
                        <h4 class="footer-box-header nomobile">Social Media</h4>
                        <ul class="social-media-footer nomobile">
                            <li><a class="social_facebookSprite" href="https://www.facebook.com/KrampUK" target="_blank" title="Facebook"></a></li>
                            <li><a class="social_twitterSprite" href="https://twitter.com/krampgroup" target="_blank" title="Twitter"></a></li>
                            <li><a class="social_youtubeSprite" href="https://www.youtube.com/user/krampgroep" target="_blank" title="Youtube"></a></li>
                            <li><a class="social_googleSprite" href="https://plus.google.com/+kramp" target="_blank" title="Google Plus"></a></li>
                            <li><a class="social_linkedinSprite" href="https://www.linkedin.com/company/kramp" target="_blank" title="Linked In"></a></li>
                        </ul>
                    </div>

                </div>
            </div>

        </div>

        <div class="footer-box">

            <h4 class="footer-box-header">item counter</h4>

            <span class="itemCounter">434,041</span>

        </div>
    </div>
</div>