    <div class="ems70" id="ems70_HomepageTop"><div class="caption" style="display:none">[HomepageTop]</div>

        <div class="ems70marketingContent" data-ad-name="HomepageTopCss2015" data-ad-id="ems70contentContainer_916504">
            <div class="ems70contentContainer" id="ems70contentContainer_916504">

                <style>
                    .homepageCarousel .carousel{
                        margin: 0px;
                        height: 375px;
                        background: gray;
                        font-family: 'Open Sans', sans-serif;
                    }

                    .homepageCarousel .carousel .item{
                        height: 375px;
                    }

                    .homepageCarousel .carousel .item.slide1{
                        background: url('http://krg-global-m.s3.amazonaws.com/corporate/kramp/HomePageSlider/CDI_Dealerlocator.jpg') no-repeat center center;
                    }

                    .homepageCarousel .carousel .item.slide2{
                        background: url('http://krg-global-m.s3.amazonaws.com/corporate/kramp/HomePageSlider/CDI_USPQuickDelivery.jpg') no-repeat center center;
                    }

                    .homepageCarousel .carousel .item.slide3{
                        background: url('http://krg-global-m.s3.amazonaws.com/corporate/kramp/HomePageSlider/CDI_KrampBrand.jpg') no-repeat center center;
                    }

                    .homepageCarousel .carousel .item.slide4{
                        background: url('http://krg-global-m.s3.amazonaws.com/corporate/kramp/HomePageSlider/SeptemberHighlight.jpg') no-repeat center center;
                    }

                    .homepageCarousel .carousel .item .TextBox{
                        bottom: 55px;
                        margin-left: 20px;
                        position: absolute;
                        max-width: 730px;
                    }

                    .homepageCarousel .carousel .item .TextBox .Title{
                        float: left;
                        clear: both;
                        font-family:"Open Sans";
                        background-color:rgba(0, 0, 0, 0.8); /* 0.8 opacity */
                        -moz-border-radius:2px;
                        border-radius:2px;
                        padding:17px; /* Hier kunnen we iets mee spelen */
                        font-size:25px;
                        margin-left:8px;
                        font-weight:bold;
                        color:white;
                    }

                    .homepageCarousel .carousel .item .TextBox .Description{
                        float: left;
                        clear: both;
                        background-color:#990000;
                        -moz-border-radius: 2px;
                        border-radius: 2px;
                        padding:11px;
                        margin-top: -4px;
                        color: #fff;
                        font-size:13px;
                    }

                    .homepageCarousel .menu{
                        background-color: rgb(0, 0, 0);
                        background-color: rgba(0, 0, 0, 0.8);
                        -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#00000000, endColorstr=#00000000)";

                        margin-top: -35px;
                        position: relative;
                    }

                    .homepageCarousel .menu .container ul{
                        margin: 0px;
                        padding: 0px;
                    }

                    .homepageCarousel .menu .container ul li{
                        float: left;
                        list-style: none;
                        margin: 0px;
                        padding: 0px;
                    }

                    .homepageCarousel .menu .container ul li span{
                        color: #8793a3;
                        font-family: 'Open Sans', sans-serif;
                        font-weight: bold;
                        text-transform: uppercase;
                        text-decoration: underline;
                        line-height: 35px;
                        padding: 0px 10px;
                        cursor: pointer;
                        display: block;
                    }

                    .homepageCarousel .menu .container ul li span.active{
                        color: #fff;
                        text-decoration: none;
                    }

                    .HomepageUbr .container{
                        position: relative;
                    }

                    .HomepageUbr .container .box{
                        width: 190px;
                        height: 260px;
                        padding: 20px;
                        position: absolute;
                        top: -355px;
                        right: 0px;
                        background: #fff;
                        font-family: 'Open Sans', sans-serif;

                        -webkit-border-radius: 4px;
                        -moz-border-radius: 4px;
                        border-radius: 4px;

                        -moz-box-shadow: 0 0 10px #aaaaaa;
                        -webkit-box-shadow: 0 0 10px #aaaaaa;
                        box-shadow: 0 0 10px #aaaaaa;
                    }

                    .HomepageUbr .container .box h2{
                        font-size: 20px;
                    }

                    .HomepageUbr .container .box ul.UbrList{
                        margin: 15px 0px 0px 20px;
                        padding: 0px;
                    }

                    .HomepageUbr .container .box ul.UbrList li.icon{
                        margin-bottom: 15px;
                    }

                    .HomepageUbr .container .box ul.UbrList li.icon.check{
                        list-style-image: url('http://krg-global-m.s3.amazonaws.com/corporate/kramp/HomePageSlider/icons/checkGreen.png');
                    }

                    .HomepageUbr .container .box ul.UbrList li.icon.play{
                        list-style-image: url('http://krg-global-m.s3.amazonaws.com/corporate/kramp/HomePageSlider/icons/playGreen.png');
                    }


                    .HomepageUbr .container .box .btn{
                        display: block;
                        margin-top: 8px;
                        font-weight: bold;
                        font-family: 'Open Sans', sans-serif;
                    }

                    @media (max-width: 979px) and (min-width: 765px){
                        .homepageCarousel .carousel .item .TextBox{
                            max-width: 500px;
                        }
                    }

                    @media (min-width: 1200px){
                        .homepageCarousel .carousel .item .TextBox{
                            max-width: 950px;
                        }
                    }

                    @media (max-width: 765px) {

                        .homepageCarousel .carousel, .homepageCarousel .carousel .item{
                            height: 200px;
                            background-size: auto 200px !important;
                        }

                        .homepageCarousel .carousel .item .TextBox{
                            width: auto;
                            margin-left: 10px;
                            margin-right: 10px;
                            bottom: 10px;
                        }

                        .homepageCarousel .carousel .item .TextBox .Title{
                            font-size: 17px;
                        }

                        .homepageCarousel .menu{
                            margin-top: 0px;
                        }

                        .homepageCarousel .menu .container ul li{
                            float: none;
                        }

                        .homepageCarousel .menu .container ul li span.active{
                            background: #404040;
                        }

                        .HomepageUbr .container .box{
                            position: relative;
                            top: 0px;
                            width: auto;

                            -webkit-border-radius: 0px;
                            -moz-border-radius: 0px;
                            border-radius: 0px;

                            -moz-box-shadow: none;
                            -webkit-box-shadow: none;
                            box-shadow: none;
                        }
                        .marketingBar .brandsHome .logos {
                            width:180px;
                        }
                    }
                </style>


            </div>
        </div>

        <div class="ems70marketingContent" data-ad-name="HomepageTopSlider2015" data-ad-id="ems70contentContainer_916505">
            <div class="ems70contentContainer" id="ems70contentContainer_916505">








                <div class="homepageCarousel">
                    <div class="carousel stepsCarousel guestCarousel slide">
                        <div class="carousel-inner">
                            <div class="item slide2">
                                <div class="container">
                                    <div class="TextBox">
			<span class="Title">
			    				450.000
			     articles available <br> direct from stock!
			</span>
                                        <a href="/shop-de/en/m/3">
                                            <span class="Description">Discover more about Kramp</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="item slide3 active">
                                <div class="container">
                                    <div class="TextBox">
                                        <span class="Title">The brand for professional <br> and intensive use</span>
                                        <a href="/shop-de/en/brand/10201/Kramp">
                                            <span class="Description">View our private brand range</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="item slide4">
                                <div class="container">
                                    <div class="TextBox">
                                        <span class="Title">Everything for your maintenance, <br> easy accessible </span>
                                        <a href="/shop-de/en/FollowEasyLink?storeId=10&amp;langId=-1&amp;easyLink=C224675">
                                            <span class="Description">Take a look at our assortment</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="menu">
                        <div class="container">
                            <ul>

                                <li><span data-to="1" class="">How will you benefit?    </span></li>
                                <li><span data-to="2" class="active">Our Kramp Brand</span></li>
                                <li><span data-to="3" class=""> In the Spotlight</span></li>
                            </ul>
                        </div>
                    </div>

                    <script type="text/javascript">
                        $(document).bind('eventModel:pageFragmentLoad', function(event) {
                            if ($(event.target).has($('.guestCarousel'))) {
                                $('.guestCarousel').carousel({interval: 8000})
                                $('.homepageCarousel .menu span').click(function(q){
                                    q.preventDefault();
                                    targetSlide = $(this).attr('data-to')-1;
                                    $('.guestCarousel').data('carousel').to(targetSlide);
                                });

                                $('.homepageCarousel .guestCarousel').bind('slide', function(e, options) {
                                    var index = $(e.relatedTarget).index();
                                    var tabs = $('.homepageCarousel .menu span');
                                    $('.homepageCarousel .menu span.active').removeClass('active');
                                    $(tabs.get(index)).addClass('active');
                                });
                            }
                        });
                    </script>
                </div>

            </div>
        </div>

        <div class="ems70marketingContent" data-ad-name="HomepageTopUbr2015" data-ad-id="ems70contentContainer_916506">
            <div class="ems70contentContainer" id="ems70contentContainer_916506">








                <div class="HomepageUbr">
                    <div class="container">
                        <div class="box">
                            <h2>The advantages</h2>
                            <ul class="UbrList">
                                <li class="icon check">
                                    More than  <b>450.000 </b>  products
                                    <br><br>						 </li>

                                <li class="icon play">
                                    Watch our <a href="https://www.youtube.com/watch?v=zGFFvXxL01w" target="_blank"><b>corporate film</b></a><br><br>
                                </li>
                            </ul>
                            <br>				<a href="/shop-de/en/LogonView" class="btn btn-warning">Login</a>
                            <a href="/shop-de/en/ms/1362" class="btn">Dealer locator</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="ems70marketingContent" data-ad-name="HomepageTopBrands2015" data-ad-id="ems70contentContainer_916507">
            <div class="ems70contentContainer" id="ems70contentContainer_916507">








                <div class="marketingBar">
                    <div class="container">
                        <div class="brandsHome">
                            <div class="logos">
                                <ul>
                                    <li>
                                        <a href="/shop-de/en/brand/152/Kawasaki"><img src="//media.kramp.com/kws/bl070/Y2C3bIBgbKJL_Ev1YfJ3_Kh1mrvgbKJLaIHd5d" alt="Kawasaki"></a>
                                    </li>
                                    <li>
                                        <a href="/shop-de/en/brand/12301/Comatrol"><img src="//media.kramp.com/kws/bl070/Y2C3bIBgbKJL_EvpbKR3JMCLbhvgbKJLaIHd5d" alt="Comatrol"></a>
                                    </li>
                                    <li>
                                        <a href="/shop-de/en/brand/36/Tyrolit"><img src="//media.kramp.com/kws/bl070/Y2C3bIBgbKJL_EvQNfCLbFDQfKlL5K7um2o2" alt="Tyrolit"></a>
                                    </li>
                                    <li>
                                        <a href="/shop-de/en/brand/10104/Grégoire-Besson"><img src="//media.kramp.com/kws/bl070/Y2C3bIBgbKJL_Ev2_Ir2bKDE5rvDJhvV5fOGbKjAbFv2bEjq_F_" alt="Grégoire-Besson"></a>
                                    </li>
                                    <li>
                                        <a href="/shop-de/en/brand/10010/Bruder"><img src="//media.kramp.com/kws/bl070/Y2C3bIBgbKJL_EvV_2rX5fCAbFv2bEjq_F_" alt="Bruder"></a>
                                    </li>
                                    <li>
                                        <a href="/shop-de/en/brand/19/Kroon-Oil"><img src="//media.kramp.com/kws/bl070/Y2C3bIBgbKJL_Ev1_IvLbIvHbhvgbKJLaIHd5d" alt="Kroon-Oil"></a>
                                    </li>
                                    <li>
                                        <a href="/shop-de/en/brand/105/Comet"><img src="//media.kramp.com/kws/bl070/Y2C3bIBgbKJL_EvpbKRDJhvgbKJLaIHd5d" alt="Comet"></a>
                                    </li>
                                    <li>
                                        <a href="/shop-de/en/brand/200/BlackBruin"><img src="//media.kramp.com/kws/bl070/Y2C3bIBgbKJL_EvVbFhpmRvV_2rHbDvgbKJLaIHd5d" alt="BlackBruin"></a>
                                    </li>
                                    <li>
                                        <a href="/shop-de/en/brand/11310/Gates"><img src="//media.kramp.com/kws/bl070/Y2C3bIBgbKJL_Ev2YfBD_RvgbKJLaIHd5d" alt="Gates"></a>
                                    </li>
                                    <li>
                                        <a href="/shop-de/en/brand/109/TeeJet"><img src="//media.kramp.com/kws/bl070/Y2C3bIBgbKJL_EvQ5Srq5fBAbFv2bEjq_F_" alt="TeeJet"></a>
                                    </li>
                                    <li>
                                        <a href="/shop-de/en/brand/3/INAFAG"><img src="//media.kramp.com/kws/bl070/Y2C3bIBgbKJL_EvHbIhA5Ih2fKlL5K7um2o2" alt="INA/FAG"></a>
                                    </li>
                                    <li>
                                        <a href="/shop-de/en/brand/1765/Dormer"><img src="//media.kramp.com/kws/bl070/Y2C3bIBgbKJL_EvXb8Ct5fCAbFv2bEjq_F_" alt="Dormer"></a>
                                    </li>
                                </ul>
                            </div>
                            <ul>
                                <li><span><a href="/shop-de/en/BrandsOverview?langId=-1&amp;storeId=10" class="action">All brands</a></span></li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="ems70marketingContent" data-ad-name="click_listPrice_fix" data-ad-id="ems70contentContainer_735507">
            <div class="ems70contentContainer" id="ems70contentContainer_735507">

                <style>
                    .highlightPromotionElements.categories.categories.categories-grid .catEntry .price .listPrice {display:none;}
                    .clickPromotionCarousel .listPrice {display:none;}
                </style>

            </div>
        </div>

    </div>

    <div class="container bodyContainer  withExtendedHeader ">
        <div class="middleContent">


            <input type="hidden" class="wtData" data-page-name="HomePage" data-page-of-interest="HomePage" data-content-group="HomePage">



            <div class="ems70" id="ems70_HomepageContentMiddle"><div class="caption" style="display:none">[HomepageContentMiddle]</div>

                <div class="ems70marketingContent" data-ad-name="HomepageContentMiddle" data-ad-id="ems70contentContainer_641514">
                    <div class="ems70contentContainer" id="ems70contentContainer_641514">

                        <div class="homeMarketing3col">

                            <div class="column1">
                                <a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=8">
                                    <img src="//krg-global-m.s3.amazonaws.com/webshopMarketing/homeMarketing3col/Block3_01.jpg" width="300" height="151" alt="">
                                </a>

                                <h1>It’s that easy.</h1>
                                <p>
                                    Our goal is to make your work as easy as possible. With Kramp, you don't have to worry about spare parts being available, leaving you free to focus fully on increasing your sales.
                                </p>

                                <a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=8" class="action">
                                    Read more
                                </a>

                            </div>

                            <div class="column2">

                                <a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=16">
                                    <img src="//krg-global-m.s3.amazonaws.com/webshopMarketing/homeMarketing3col/Block3_02.jpg" width="300" height="151" alt="">
                                </a>

                                <h1>Services with added value</h1>
                                <p>
                                    We have translated our sixty years of experience into a host of services designed to bring you added value. These services are centred around ease of ordering, efficiency and sharing knowledge and experience.
                                </p>

                                <a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=16" class="action">
                                    Read more
                                </a>

                            </div>

                            <div class="column3">

                                <a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=12">
                                    <img src="//krg-global-m.s3.amazonaws.com/webshopMarketing/homeMarketing3col/Block3_03.jpg" width="300" height="151" alt="">
                                </a>

                                <h1>Our markets</h1>
                                <p>
                                    Whether you operate in the agricultural market, forest &amp; grasscare sector, in construction or in mechanical engineering (OEM): as a one-stop supplier and technical specialist, we aim to add solid value to your business. We understand your market and we are aware of just how many options there are to make your business simple and efficient. Our aim is to help you turn spare parts into a profitable activity.
                                </p>

                                <a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=12" class="action">
                                    Read more
                                </a>

                            </div>

                        </div>

                    </div>
                </div>

            </div>


            <div class="ems70" id="ems70_HomepageContentBottom"><div class="caption" style="display:none">[HomepageContentBottom]</div>

                <div class="ems70marketingContent" data-ad-name="HomepageContentBottom" data-ad-id="ems70contentContainer_641520">
                    <div class="ems70contentContainer" id="ems70contentContainer_641520">

                        <div class="homeMarketing2col">

                            <div class="column1">

                                <a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=3">
                                    <img src="//krg-global-m.s3.amazonaws.com/webshopMarketing/homeMarketing2col/Block3_04.jpg" alt="">
                                </a>

                                <h1>About Kramp</h1>
                                <p>
                                    As a one-stop supplier of spare parts, technical services and business solutions, we act as a strategic partner to businesses in the agricultural sector, forest &amp; grasscare sector, in construction and in OEM.
                                </p>

                                <a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=3" class="action">
                                    Read more
                                </a>

                            </div>

                            <div class="column2">

                                <a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=322">
                                    <img src="//krg-global-m.s3.amazonaws.com/webshopMarketing/homeMarketing2col/Block3_05.jpg" alt="">
                                </a>

                                <h1>Close to the customer</h1>
                                <p>
                                    We are happy to push the boundaries for our customers.  We are now represented at 20 sites in 16 European countries and we have our own sales team in China. We continue to value the local nature of our company. You are simply doing business with a local partner; one who knows your market, speaks your language and who is never far away.
                                </p>

                                <a href="/shop-de/en/MarketingPageView?langId=-1&amp;storeId=10&amp;nodeId=322" class="action">
                                    Contact us
                                </a>

                            </div>

                        </div>

                    </div>
                </div>

            </div>

            <div class="clearBoth"></div>

        </div>

    </div>

    <div class="ems70" id="ems70_HomepageBottom"><div class="caption" style="display:none">[HomepageBottom]</div>

    </div>
