
    <a class="logo" href="<?php echo $block->getUrl(''); ?>">

        <style>
            .logo {
                background: url("<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>") left center no-repeat;
            }
            .logo {
                float: left;
                width: <?php echo $block->getLogoWidth()?>px;
                height: <?php echo $block->getLogoHeight()?>px;
                margin: 11px 55px 10px 10px;
                clear: left;
                display: block;
            }
            .logo {
                text-indent: -119988px;
            }
            a {
                color: #000;
                text-decoration: none;
            }
        </style>

    </a>




